language: android
jdk: openjdk7
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra
    - addon
    - sys-img-armeabi-v7a-android-19
env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
before_script:
  - android list target
  - echo no | android create avd --force --name test --target android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
script:
  - ./gradlew connectedAndroidTest
